// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Processos.Models;

#nullable disable

namespace Processos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230927224535_M0001")]
    partial class M0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Processos.Models.Tipo_Processo", b =>
                {
                    b.Property<int>("codigoTipoProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoTipoProcesso"));

                    b.Property<string>("nomeTipoProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoTipoProcesso");

                    b.ToTable("TIPO_PROCESSO");
                });
#pragma warning restore 612, 618
        }
    }
}
